version: '3.8'
services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
      - ./academytrack.sql:/docker-entrypoint-initdb.d/academytrack.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data: {}
